version: "3"

services:
  app:
    container_name: example_app
    restart: always
    build: .
    ports:
      - "5000:3000"
    # link volumes location (de esta manera vemos las modificaciones del host dentro de container)
    volumes:
      - .:/usr/src/app
  mongodb:
    container_name: mongo_database
    image: mongo
    restart: always
    ports:
      - 27017:27017
    #environment:
    #- MONGO_INITDB_ROOT_USERNAME=admin
    #- MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
  mongo-express:
    container_name: mongo_api
    image: mongo-express
    #restart: always -> por error de Could not connect to database using connectionString: mongodb://admin:password@mongodb:27017/"
    restart: always
    ports:
      - 8081:8081
    environment:
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
