version: "3"

services:
  app:
    container_name: app
    # restart: always
    build: .
    ports:
      - "3535:3535"
    volumes:
      - .:/usr/src/app
  postgres-db:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
    driver: local
